/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.schulverwaltungsprogramm;

import java.awt.Color;
import java.util.ArrayList;
import java.awt.Container;
import java.awt.Component;
import java.util.Arrays;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.JList;

/**
 *
 * @author enaci
 */
public class FachFrame extends javax.swing.JFrame {

    /**
     * Creates new form FachFrame
     */
    public FachFrame() {
        initComponents();
        setDisabled(addFachPnl, false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        addFachPnl = new javax.swing.JPanel();
        insertFachBtn = new javax.swing.JButton();
        fachnameLbl = new javax.swing.JLabel();
        themenLbl = new javax.swing.JLabel();
        fachnameTf = new javax.swing.JTextField();
        themenTf = new javax.swing.JTextField();
        lehrkraftLbl = new javax.swing.JLabel();
        uhrzeitLbl = new javax.swing.JLabel();
        dauernLbl = new javax.swing.JLabel();
        uhrzeitTf = new javax.swing.JTextField();
        dauerTf = new javax.swing.JTextField();
        lehrerCBox = new javax.swing.JComboBox<>();
        indexLbl = new javax.swing.JLabel();
        fachIndexTf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        addFachBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fachDelBtn = new javax.swing.JButton();
        fachListBtn = new javax.swing.JButton();
        deleteFachPnl = new javax.swing.JPanel();
        delFachMsgLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        delFachNameTf = new javax.swing.JTextField();
        fachLöschenBtn = new javax.swing.JButton();
        fachDelMsgLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fachTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1300, 750));

        backBtn.setText("Go Back");
        backBtn.setPreferredSize(new java.awt.Dimension(75, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addFachPnl.setBackground(new java.awt.Color(255, 255, 255));
        addFachPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        insertFachBtn.setText("Hinzufügen");
        insertFachBtn.setToolTipText("");
        insertFachBtn.setPreferredSize(new java.awt.Dimension(80, 50));
        insertFachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertFachBtnActionPerformed(evt);
            }
        });

        fachnameLbl.setText("Fachname:");

        themenLbl.setText("Themen:");

        lehrkraftLbl.setText("Lehrkraft:");

        uhrzeitLbl.setText("Uhrzeit:");

        dauernLbl.setText("Dauern:");

        lehrerCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wählt ein Lehrer", "Yiğit Keskin", "Musab Çekmeyerek", "Alişan Ok", "Cem Dikgöz", "Emin Attila", "Hakkı Tunç", "Havva Yakar", "Şeyda Ulukaya", "Hülya Savcı", "Melisa Yılmaz", "Eren Esencik", "Makarov Anadolu", " " }));
        lehrerCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lehrerCBoxActionPerformed(evt);
            }
        });

        indexLbl.setText("Index:");

        javax.swing.GroupLayout addFachPnlLayout = new javax.swing.GroupLayout(addFachPnl);
        addFachPnl.setLayout(addFachPnlLayout);
        addFachPnlLayout.setHorizontalGroup(
            addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFachPnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addFachPnlLayout.createSequentialGroup()
                            .addComponent(fachnameLbl)
                            .addGap(64, 64, 64))
                        .addGroup(addFachPnlLayout.createSequentialGroup()
                            .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dauernLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uhrzeitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(75, 75, 75)))
                    .addGroup(addFachPnlLayout.createSequentialGroup()
                        .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lehrkraftLbl)
                            .addComponent(themenLbl))
                        .addGap(72, 72, 72)))
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertFachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fachnameTf)
                    .addComponent(themenTf)
                    .addComponent(uhrzeitTf, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(dauerTf)
                    .addComponent(lehrerCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFachPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indexLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fachIndexTf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addFachPnlLayout.setVerticalGroup(
            addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFachPnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fachnameLbl)
                    .addComponent(fachnameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexLbl)
                    .addComponent(fachIndexTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themenLbl)
                    .addComponent(themenTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lehrkraftLbl)
                    .addComponent(lehrerCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uhrzeitLbl)
                    .addComponent(uhrzeitTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(addFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dauernLbl)
                    .addComponent(dauerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(insertFachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));

        addFachBtn.setText("Neu Fach hinzufügen");
        addFachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFachBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Operationen");

        fachDelBtn.setText("Fach Löschen");
        fachDelBtn.setPreferredSize(new java.awt.Dimension(160, 28));

        fachListBtn.setText("Fachlist erstellen");
        fachListBtn.setPreferredSize(new java.awt.Dimension(160, 28));
        fachListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fachListBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(addFachBtn)
                        .addGap(191, 191, 191)
                        .addComponent(fachDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(fachListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fachListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fachDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteFachPnl.setBackground(new java.awt.Color(255, 255, 255));
        deleteFachPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        delFachMsgLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delFachMsgLbl.setText("Der Name des Faches einstecken");

        nameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameLbl.setText("Name:");

        fachLöschenBtn.setText("Löschen");
        fachLöschenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fachLöschenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteFachPnlLayout = new javax.swing.GroupLayout(deleteFachPnl);
        deleteFachPnl.setLayout(deleteFachPnlLayout);
        deleteFachPnlLayout.setHorizontalGroup(
            deleteFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteFachPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fachLöschenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(deleteFachPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fachDelMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deleteFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(delFachMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(deleteFachPnlLayout.createSequentialGroup()
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(delFachNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        deleteFachPnlLayout.setVerticalGroup(
            deleteFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteFachPnlLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(delFachMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(deleteFachPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(delFachNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(fachDelMsgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fachLöschenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        fachTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fachname", "Lehrer", "Uhrzeit", "Dauer", "Themen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(fachTbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addFachPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteFachPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFachPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteFachPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addFachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFachBtnActionPerformed
        if(insertFachBtn.isEnabled()) 
            setDisabled(addFachPnl, false);
         else if(!insertFachBtn.isEnabled())
             setDisabled(addFachPnl, true);
    }//GEN-LAST:event_addFachBtnActionPerformed

    private void lehrerCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lehrerCBoxActionPerformed
        
    }//GEN-LAST:event_lehrerCBoxActionPerformed

    private void insertFachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertFachBtnActionPerformed
        try{
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        
        String userName = new com.sun.security.auth.module.NTSystem().getName();
       Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
        
        Fach fh = new Fach(fachnameTf.getText(), themenTf.getText(), (String)lehrerCBox.getSelectedItem(), uhrzeitTf.getText(), dauerTf.getText());
        
        String sql = "INSERT INTO fachTbl ([id], [Fachname], [Lehrer], [Uhrzeit], [Dauer], [Themen]) VALUES(?, ?, ?, ?, ?, ?)";
        
        PreparedStatement stmt = connection.prepareStatement(sql);
        
        stmt.setString(1, fachIndexTf.getText());
        stmt.setString(2, fh.getFachname());
        stmt.setString(3, fh.getLehrer());
        stmt.setString(4, fh.getUhrzeit());
        stmt.setString(5, fh.getDauer());
        stmt.setString(6, fh.getThemen());
        stmt.executeUpdate();
        
        String klassSql = "INSERT INTO klasseTbl ([Fachname]) VALUES(?)";
        stmt = connection.prepareStatement(klassSql);
        stmt.setString(1, fh.getFachname());
        stmt.executeUpdate();
        connection.close();
        fh = new Fach();
        }catch(Exception e){
            System.out.println("Couldn't connect with database");
        }
    }//GEN-LAST:event_insertFachBtnActionPerformed

    private void fachListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fachListBtnActionPerformed
       
        try{
            DefaultTableModel aModel = (DefaultTableModel)fachTbl.getModel();
            aModel.setRowCount(0);
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String userName = new com.sun.security.auth.module.NTSystem().getName();
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
            
            String sql = "select id, Fachname, Lehrer, Uhrzeit, Dauer, Themen from fachTbl";
            
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rs.next()){
                Object[] objects = new Object[colNo];
                for(int i = 0; i <colNo; i++){
                    objects[i] = rs.getObject(i+1);
                }
                aModel.addRow(objects);
                fachTbl.setModel(aModel);
                connection.close();
            }
        }catch(Exception e){
            System.out.println("Error in connection");
        }
        
    }//GEN-LAST:event_fachListBtnActionPerformed

    private void fachLöschenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fachLöschenBtnActionPerformed
        try{
         Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
         String userName = new com.sun.security.auth.module.NTSystem().getName();
         Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
         
         String delSql = "DELETE FROM fachTbl WHERE id = ?";
         PreparedStatement delStmt = connection.prepareStatement(delSql);
         delStmt.setString(1, delFachNameTf.getText());
         delStmt.executeUpdate();
      
         fachDelMsgLbl.setForeground(Color.GREEN);
         fachDelMsgLbl.setText("Fach " + fachIndexTf.getText() + " ist gelöscht!");
         connection.close();
        }catch(Exception e){
            fachDelMsgLbl.setForeground(Color.RED);
            fachDelMsgLbl.setText("Konnte das Fach nicht finden!");
        }
    }//GEN-LAST:event_fachLöschenBtnActionPerformed
    
    private Component[] getComponents(Component container) {
        ArrayList<Component> list = null;

        try {
            list = new ArrayList<Component>(Arrays.asList(
                  ((Container) container).getComponents()));
            for (int index = 0; index < list.size(); index++) {
                for (Component currentComponent : getComponents(list.get(index))) {
                    list.add(currentComponent);
                }
            }
        } catch (ClassCastException e) {
            list = new ArrayList<Component>();
        }

        return list.toArray(new Component[list.size()]);
        }
   
   private void setDisabled(Component container, boolean enabled){
       for(Component component : getComponents(container)){
           component.setEnabled(enabled);
       }
   }
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFachBtn;
    private javax.swing.JPanel addFachPnl;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField dauerTf;
    private javax.swing.JLabel dauernLbl;
    private javax.swing.JLabel delFachMsgLbl;
    private javax.swing.JTextField delFachNameTf;
    private javax.swing.JPanel deleteFachPnl;
    private javax.swing.JButton fachDelBtn;
    private javax.swing.JLabel fachDelMsgLbl;
    private javax.swing.JTextField fachIndexTf;
    private javax.swing.JButton fachListBtn;
    private javax.swing.JButton fachLöschenBtn;
    private javax.swing.JTable fachTbl;
    private javax.swing.JLabel fachnameLbl;
    private javax.swing.JTextField fachnameTf;
    private javax.swing.JLabel indexLbl;
    private javax.swing.JButton insertFachBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lehrerCBox;
    private javax.swing.JLabel lehrkraftLbl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel themenLbl;
    private javax.swing.JTextField themenTf;
    private javax.swing.JLabel uhrzeitLbl;
    private javax.swing.JTextField uhrzeitTf;
    // End of variables declaration//GEN-END:variables
}
