/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.schulverwaltungsprogramm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;

/**
 *
 * @author enaci
 */
public class KlasseFrame extends javax.swing.JFrame {

    /**
     * Creates new form KlasseFrame
     */
    public KlasseFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        klassePnl = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studTbl = new javax.swing.JTable();
        addStudToFach = new javax.swing.JPanel();
        studLbl = new javax.swing.JLabel();
        klassLbl = new javax.swing.JLabel();
        insertStudToKlasseBtn = new javax.swing.JButton();
        stud1Tf = new javax.swing.JTextField();
        klassIdTf = new javax.swing.JTextField();
        stud2Tf = new javax.swing.JTextField();
        stud3Tf = new javax.swing.JTextField();
        stud5Tf = new javax.swing.JTextField();
        stud6Tf = new javax.swing.JTextField();
        stud4Tf = new javax.swing.JTextField();
        stud7Tf = new javax.swing.JTextField();
        stud8Tf = new javax.swing.JTextField();
        stud9Tf = new javax.swing.JTextField();
        stud10Tf = new javax.swing.JTextField();
        addStudToFachBtn = new javax.swing.JButton();
        listStudBtn = new javax.swing.JButton();
        klasseListenPnl = new javax.swing.JPanel();
        klasseListPnl = new javax.swing.JScrollPane();
        klasseListTbl = new javax.swing.JTable();
        listKlasseBtn = new javax.swing.JButton();
        studKlassePnl = new javax.swing.JPanel();
        klasseListPnl1 = new javax.swing.JScrollPane();
        klasseListTbl2 = new javax.swing.JTable();
        studIdListLbl = new javax.swing.JLabel();
        klassIdListTf = new javax.swing.JTextField();
        listStudKlasseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        alleKlassenBtn = new javax.swing.JButton();
        studKlasseListBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1750, 750));

        klassePnl.setPreferredSize(new java.awt.Dimension(1750, 750));

        backBtn.setText("Go Back");
        backBtn.setPreferredSize(new java.awt.Dimension(75, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));

        studTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Vorname", "Nachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studTbl.setPreferredSize(new java.awt.Dimension(175, 400));
        jScrollPane1.setViewportView(studTbl);
        if (studTbl.getColumnModel().getColumnCount() > 0) {
            studTbl.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addStudToFach.setBackground(new java.awt.Color(255, 255, 255));
        addStudToFach.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        addStudToFach.setPreferredSize(new java.awt.Dimension(440, 400));

        studLbl.setText("Student ID:");

        klassLbl.setText("Klasse ID:");

        insertStudToKlasseBtn.setText("Hinzufügen");
        insertStudToKlasseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertStudToKlasseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addStudToFachLayout = new javax.swing.GroupLayout(addStudToFach);
        addStudToFach.setLayout(addStudToFachLayout);
        addStudToFachLayout.setHorizontalGroup(
            addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudToFachLayout.createSequentialGroup()
                .addGroup(addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStudToFachLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(insertStudToKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addStudToFachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(klassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stud2Tf, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(stud1Tf)
                            .addComponent(stud3Tf)
                            .addComponent(stud5Tf)
                            .addComponent(stud6Tf)
                            .addComponent(stud4Tf)
                            .addComponent(stud7Tf)
                            .addComponent(stud8Tf)
                            .addComponent(stud9Tf)
                            .addComponent(stud10Tf)
                            .addComponent(klassIdTf))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        addStudToFachLayout.setVerticalGroup(
            addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStudToFachLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studLbl)
                    .addComponent(stud1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud4Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(stud5Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud6Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud7Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud8Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud9Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stud10Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(addStudToFachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klassIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(klassLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(insertStudToKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addStudToFachBtn.setText("Student zu Klasse hinzufügen");
        addStudToFachBtn.setPreferredSize(new java.awt.Dimension(214, 40));

        listStudBtn.setText("Studenten Listen");
        listStudBtn.setPreferredSize(new java.awt.Dimension(214, 40));
        listStudBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudBtnActionPerformed(evt);
            }
        });

        klasseListenPnl.setBackground(new java.awt.Color(255, 255, 255));
        klasseListenPnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        klasseListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fachname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        klasseListTbl.setPreferredSize(new java.awt.Dimension(175, 400));
        klasseListPnl.setViewportView(klasseListTbl);
        if (klasseListTbl.getColumnModel().getColumnCount() > 0) {
            klasseListTbl.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        javax.swing.GroupLayout klasseListenPnlLayout = new javax.swing.GroupLayout(klasseListenPnl);
        klasseListenPnl.setLayout(klasseListenPnlLayout);
        klasseListenPnlLayout.setHorizontalGroup(
            klasseListenPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klasseListenPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(klasseListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        klasseListenPnlLayout.setVerticalGroup(
            klasseListenPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klasseListenPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(klasseListPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        listKlasseBtn.setText("Klasse Listen");
        listKlasseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listKlasseBtnActionPerformed(evt);
            }
        });

        studKlassePnl.setBackground(new java.awt.Color(255, 255, 255));
        studKlassePnl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        studKlassePnl.setPreferredSize(new java.awt.Dimension(500, 6));

        klasseListTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID 1", "ID 2", "ID 3", "ID 4", "ID 5", "ID 6", "ID 7", "ID 8", "ID 9", "ID 10"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        klasseListTbl2.setPreferredSize(new java.awt.Dimension(175, 400));
        klasseListPnl1.setViewportView(klasseListTbl2);

        studIdListLbl.setText("Bitte ein Klasse ID einstecken:");

        listStudKlasseBtn.setText("List");
        listStudKlasseBtn.setPreferredSize(new java.awt.Dimension(140, 40));
        listStudKlasseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudKlasseBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Wollen Sie alle Klassen sehen ?");

        alleKlassenBtn.setText("Alle Klassen");
        alleKlassenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alleKlassenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studKlassePnlLayout = new javax.swing.GroupLayout(studKlassePnl);
        studKlassePnl.setLayout(studKlassePnlLayout);
        studKlassePnlLayout.setHorizontalGroup(
            studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studKlassePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studKlassePnlLayout.createSequentialGroup()
                        .addGroup(studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studIdListLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(studKlassePnlLayout.createSequentialGroup()
                                .addComponent(klassIdListTf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(klasseListPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studKlassePnlLayout.createSequentialGroup()
                        .addGroup(studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listStudKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studKlassePnlLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(alleKlassenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        studKlassePnlLayout.setVerticalGroup(
            studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studKlassePnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(studIdListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(klassIdListTf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(listStudKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(studKlassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alleKlassenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(studKlassePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(klasseListPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studKlasseListBtn.setText("Students Fächer Listen");

        javax.swing.GroupLayout klassePnlLayout = new javax.swing.GroupLayout(klassePnl);
        klassePnl.setLayout(klassePnlLayout);
        klassePnlLayout.setHorizontalGroup(
            klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klassePnlLayout.createSequentialGroup()
                .addGroup(klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(klassePnlLayout.createSequentialGroup()
                        .addGroup(klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(klassePnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(klassePnlLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(listStudBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(klassePnlLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(addStudToFachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)
                                .addComponent(listKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(studKlasseListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(klassePnlLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(addStudToFach, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(klasseListenPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(studKlassePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE))))
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(255, 255, 255))
        );
        klassePnlLayout.setVerticalGroup(
            klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klassePnlLayout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listStudBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudToFachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listKlasseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studKlasseListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(klassePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(klasseListenPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudToFach, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studKlassePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(klassePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(klassePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertStudToKlasseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertStudToKlasseBtnActionPerformed
        
        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String userName = new com.sun.security.auth.module.NTSystem().getName();
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
            
            
            
            String sql = "UPDATE klasseTbl  SET Student1=?, Student2=?, Student3=?, Student4=?, Student5=?, Student6=?, Student7=?, Student8=?, Student9=?, Student10=? WHERE klass_id =? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, stud1Tf.getText());
            stmt.setString(2, stud2Tf.getText());
            stmt.setString(3, stud3Tf.getText());
            stmt.setString(4, stud4Tf.getText());
            stmt.setString(5, stud5Tf.getText());
            stmt.setString(6, stud6Tf.getText());
            stmt.setString(7, stud7Tf.getText());
            stmt.setString(8, stud8Tf.getText());
            stmt.setString(9, stud9Tf.getText());
            stmt.setString(10,stud10Tf.getText());
            stmt.setString(11, klassIdTf.getText());
            stmt.executeUpdate();
            
            
            connection.close();
            
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_insertStudToKlasseBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void listStudBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudBtnActionPerformed
        try{
            DefaultTableModel aModel = (DefaultTableModel) studTbl.getModel();

            aModel.setRowCount(0);

            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String userName = new com.sun.security.auth.module.NTSystem().getName();
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
            String sql = "select id ,Vorname, Nachname from tblStudenten";
            PreparedStatement pst = connection.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rs.next()){
                Object[] objects = new Object[colNo];
                for(int i = 0; i < colNo; i++){
                    objects[i] = rs.getObject(i+1);
                }
                aModel.addRow(objects);
                studTbl.setModel(aModel);
                connection.close();
            }
        }catch(Exception e){
            System.out.println("Error in connection");
        }
    }//GEN-LAST:event_listStudBtnActionPerformed

    private void listKlasseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKlasseBtnActionPerformed
        
        try{
            DefaultTableModel aModel = (DefaultTableModel)klasseListTbl.getModel();
            aModel.setRowCount(0);
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String userName = new com.sun.security.auth.module.NTSystem().getName();
            Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
            
            String sql = "select klass_id, Fachname from klasseTbl";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rs.next()){
                Object[] objects = new Object[colNo];
                for(int i = 0; i <colNo; i++){
                    objects[i] = rs.getObject(i+1);
                }
                aModel.addRow(objects);
                klasseListTbl.setModel(aModel);
                connection.close();
            }
            
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_listKlasseBtnActionPerformed

    private void listStudKlasseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudKlasseBtnActionPerformed
        
        try{
            
         DefaultTableModel aModel = (DefaultTableModel)klasseListTbl2.getModel();
        aModel.setRowCount(0);
        
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        String userName = new com.sun.security.auth.module.NTSystem().getName();
        Connection connection = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\" + userName + "\\Documents\\NetBeansProjects\\Schulverwaltungsprogramm\\src\\main\\studentDB.accdb");
        
        String sql = "select Student1, Student2, Student3, Student4, Student5, Student6, Student7, Student8, Student9, Student10 from klasseTbl where klass_id =? ";
        PreparedStatement stmt = connection.prepareStatement(sql);
        
        stmt.setString(1, klassIdListTf.getText());
        ResultSet rs = stmt.executeQuery();
        
        java.sql.ResultSetMetaData rsmd = rs.getMetaData();
            int colNo = rsmd.getColumnCount();
            while(rs.next()){
                Object[] objects = new Object[colNo];
                for(int i = 0; i <colNo; i++){
                    objects[i] = rs.getObject(i+1);
                }
                aModel.addRow(objects);
                klasseListTbl2.setModel(aModel);
                
            }
        connection.close();
            
            
        }catch(Exception e){
            System.out.println("Error in connection");
        }
    }//GEN-LAST:event_listStudKlasseBtnActionPerformed

    private void alleKlassenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alleKlassenBtnActionPerformed
        this.dispose();
        new AlleKlassenFrame().setVisible(true);
    }//GEN-LAST:event_alleKlassenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStudToFach;
    private javax.swing.JButton addStudToFachBtn;
    private javax.swing.JButton alleKlassenBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton insertStudToKlasseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField klassIdListTf;
    private javax.swing.JTextField klassIdTf;
    private javax.swing.JLabel klassLbl;
    private javax.swing.JScrollPane klasseListPnl;
    private javax.swing.JScrollPane klasseListPnl1;
    private javax.swing.JTable klasseListTbl;
    private javax.swing.JTable klasseListTbl2;
    private javax.swing.JPanel klasseListenPnl;
    private javax.swing.JPanel klassePnl;
    private javax.swing.JButton listKlasseBtn;
    private javax.swing.JButton listStudBtn;
    private javax.swing.JButton listStudKlasseBtn;
    private javax.swing.JTextField stud10Tf;
    private javax.swing.JTextField stud1Tf;
    private javax.swing.JTextField stud2Tf;
    private javax.swing.JTextField stud3Tf;
    private javax.swing.JTextField stud4Tf;
    private javax.swing.JTextField stud5Tf;
    private javax.swing.JTextField stud6Tf;
    private javax.swing.JTextField stud7Tf;
    private javax.swing.JTextField stud8Tf;
    private javax.swing.JTextField stud9Tf;
    private javax.swing.JLabel studIdListLbl;
    private javax.swing.JButton studKlasseListBtn;
    private javax.swing.JPanel studKlassePnl;
    private javax.swing.JLabel studLbl;
    private javax.swing.JTable studTbl;
    // End of variables declaration//GEN-END:variables
}
